consumer_key = '1lCXIIuncfUV1q4dGbBI9apQj'
consumer_secret = 'y6HF7lfHswdB5aQv0eEzv8voc0ioyO7Ztb1zbm1xyTGoIzMtDk'
access_token = '199591857-jYRO6egAKIaFPRRBvvKocoKwHtDowBCbNjTYvDce'
access_token_secret = 'Nek8ceYCmThjRSO9GIsfWeSr8ww7SvvpDYBRZJBBb2HaO'
#from twitterKey import consumer_key,consumer_secret,access_token,access_token_secret
